#!/bin/bash
thresholds=(15 40 95 100)
prefixes=("\uf112" "\uf115" "\uf114" "\uf113")
colors=("#dc322f" "#b58900" "#839496" "#859900")
charging_prefix="\uf111"

battery=${1:-BAT0}
warn_percent=7
hibernate_percent=5

scriptname="$(basename $0)"

logfile="${HOME}/.local/var/log/${scriptname}.log"
exec 3>&1
exec 1>${logfile}
exec 2>&1

battery_capacity=$(cat /sys/class/power_supply/${battery}/capacity)

for i in $(seq 0 $((${#thresholds[@]}-1))); do
    if [ $battery_capacity -le ${thresholds[i]} ]; then
        prefix=${prefixes[i]}
        color=${colors[i]}
        break
    fi
done

battery_status=$(cat /sys/class/power_supply/${battery}/status)

if [ "$battery_status" = "Charging" ]; then
    prefix=$charging_prefix
else
    battery_current_now=$(cat /sys/class/power_supply/${battery}/current_now)
    battery_charge_now=$(cat /sys/class/power_supply/${battery}/charge_now)
    minutes_remaining=$(($battery_charge_now*60/$battery_current_now))
    hours_remaining=$(($minutes_remaining/60))
    minutes_remaining_partial=$(($minutes_remaining%60))
    if [ $minutes_remaining_partial -lt 10 ]; then
        minutes_remaining_partial="0$minutes_remaining_partial"
    fi
    time_remaining="$hours_remaining:$minutes_remaining_partial"
fi

short_text="$prefix $battery_capacity%"
full_text=$short_text
[ -n $time_remaining ] && full_text="$full_text $time_remaining"

exec >&3

echo -e $full_text
echo -e $short_text
[ -n "$color" ] && echo $color

exit 0
