#!/bin/bash
prefix="\uf294"
color="#859900"

iface="${1:-bnep0}"

ipv4addrs=($(ip addr show "${iface}" 2>/dev/null | perl -ne 'print "$1\n" if /inet (\S+).*scope global/'))
ipv6addrs=($(ip addr show "${iface}" 2>/dev/null | perl -ne 'print "$1\n" if /inet6 (\S+).*scope global/'))
if [ "${#ipv4addrs}" -eq 0 ] && [ "${#ipv6addrs}" -eq 0 ]; then
    exit 0
fi

full_text="${prefix} ${ipv4addrs[*]} ${ipv6addrs[0]}"
short_text="${prefix} ${ipv4addrs[*]}"

echo -e "${full_text}"
echo -e "${short_text}"
[ -n "$color" ] && echo "${color}"

exit 0
