#!/bin/bash
prefix="\uf0a3"

brightness="$(xbacklight 2>/dev/null)"

[ -z "${brightness}" ] && exit 0

short_text="${prefix} ${brightness%%.*}%"
full_text="${short_text}"

echo -e "${full_text}"
echo -e "${short_text}"

exit 0
