#!/bin/bash
prefix="\uf0a3"

backlight_curr_brightness="$(cat /sys/class/backlight/intel_backlight/brightness)"
backlight_max_brightness="$(cat /sys/class/backlight/intel_backlight/max_brightness)"
backlight_curr_brightness_pct="$((100*backlight_curr_brightness/backlight_max_brightness))"

[ -z "${backlight_curr_brightness_pct}" ] && exit 0

short_text="${prefix} ${backlight_curr_brightness_pct}%"
full_text="${short_text}"

echo -e "${full_text}"
echo -e "${short_text}"

exit 0
