#!/bin/bash
scriptdir=$(dirname $0)

iface=$(ip route | perl -lne 'print $1 if /^default\b.*?\sdev\s(\S+)/')
case $iface in
    tun*|ppp*)
    $scriptdir/vpn $iface
    ;;
    wlan*)
    $scriptdir/wifi $iface
    ;;
    bnep*)
    $scriptdir/bluetooth $iface
    ;;
    *)
    $scriptdir/ethernet $iface
    ;;
esac
