#!/bin/bash
scriptdir="$(dirname "${BASH_SOURCE[0]}")"

iface="$(ip r | awk '$1 == "default" { print $NF; exit }')"
case $iface in
    tun*|ppp*)
    $scriptdir/vpn $iface
    ;;
    wlan*)
    $scriptdir/wifi $iface
    ;;
    bnep*)
    $scriptdir/bluetooth $iface
    ;;
    *)
    $scriptdir/ethernet $iface
    ;;
esac
