#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# with changes Copyright (C) 2014 Mark Stillwell <mark@stillwell.me>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

prefix="\uf341"
iface="${1:-eth0}"

scriptname="$(basename $0)"

logfile="${HOME}/.local/var/log/${scriptname}.log"
exec 3>&1
exec 1>${logfile}
exec 2>&1

#state="$(cat /sys/class/net/$iface/operstate 2>/dev/null)"
#if [ "$state" != "up" ]; then
#	exit 0
#fi

ipv4addrs=($(ip addr show ${iface} | perl -ne 'print "$1\n" if /inet (\S+).*scope global/'))
ipv6addrs=($(ip addr show ${iface} | perl -ne 'print "$1\n" if /inet6 (\S+).*scope global/'))

[ -z "${ipv4addrs[0]}${ipv6addrs[0]}" ] && exit 0

short_text="$prefix ${ipv4addrs[0]}"
full_text="$prefix ${ipv4addrs[@]} ${ipv6addrs[0]}"

exec >&3

echo -e $full_text
echo -e $short_text

exit 0
