#!/bin/bash
prefix="\uf0ac"

# ifconfig.co is another option
externalip="$(curl -s https://freegeoip.net/csv/ | perl -lne 'print $1 if /^((?:\d{1,3}\.){3}\d{1,3}),/')"
[ -z "${externalip}" ] && externalip="$(curl -s https://ifconfig.co/ip 2>/dev/null)"
[ -z "${externalip}" ] && externalip="$(curl -s https://ipinfo.io/ip 2>/dev/null)"
[ -z "${externalip}" ] && exit 0

iface="$(ip r | perl -ne 'print "$1\n" if /^default\s.*\sdev\s([^\s]+)/')"
addrs=($(ip addr show "${iface}" | perl -ne 'print "$1\n" if /inet (.+)\/.*scope global/'))
defaultip="${addrs[0]}"
[ "${externalip}" = "${defaultip}" ] && exit 0

echo -e "${prefix} ${externalip}"

exit 0
