#!/bin/bash
prefix="" 
nm-online || exit 0
externalip=$(curl -s ifconfig.me/ip)
defaultdev=$(ip route | perl -ne 'print "$1\n" if /^default\s.*\sdev\s([^\s]+)/')
defaultdevaddrs=($(ip addr show ${iface} | perl -ne 'print "$1\n" if /inet (.+)\/.*scope global/'))
defaultip=${defaultdevaddrs[0]}

full_text="$prefix $externalip"

if [ -n "$externalip" ] && [ "$externalip" != "$defaultip" ]; then
    echo $full_text
fi

exit 0
