#!/bin/bash
scriptname="$(basename $0)"

logfile="${HOME}/.local/var/log/${scriptname}.log"
exec 3>&1
exec 1>${logfile}
exec 2>&1

rundir="${XDG_RUNTIME_DIR:-${HOME}/.local/var/run}/mailsync"
if ls ${rundir}/*.error >/dev/null 2>/dev/null; then
    echo -e " \uf132: mail sync error"
    exit 33
fi

lockdir="${XDG_RUNTIME_DIR:-${HOME}/.local/var}/mailsync.lock"
pidfile="${lockdir}/PID"
otherpid=$(cat ${pidfile} 2>/dev/null)
othercmd=$(ps --no-headers --format command --pid ${otherpid} 2>/dev/null)
if ! [[ "${othercmd}" =~ .*mailsync.* ]]; then
    exit 0
fi
  
exec >&3

echo -e "\uf021\uf132"
