#!/bin/bash

info=""
exitcode=0

rundir="${XDG_RUNTIME_DIR:-${HOME}/.local/var/run}/mrsync"
pidfile="${rundir}/PID"
otherpid=$(cat "${pidfile}" 2>/dev/null)
othercmd=$(ps --no-headers --format command --pid "${otherpid}" 2>/dev/null)
if [[ "${othercmd}" =~ .*mrsync.* ]]; then
    info="\uf021"
fi

if find "${rundir}" -name '*.error' 2>/dev/null | read -r; then
    exitcode=33
fi

if [ -n "$info" ] || [ $exitcode -ne 0 ]; then
    #echo -e "$info\uf233"
    echo -e "$info\ue709"
fi

exit "$exitcode"
