#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2014 Mark Stillwell <mark@stillwell.me>
# with changes Copyright (C) 2014 Mark Stillwell <mark@stillwell.me>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
prefix="\uf341"

thresholds=(15 30 50 100)
prefixes=("\uf25c" "\uf25c" "\uf25c" "\uf25c")
colors=("#dc322f" "#b58900" "#839496" "#859900")

iface="${1:-wlan0}"

scriptname="$(basename $0)"

logfile="${HOME}/.local/var/log/${scriptname}.log"
exec 3>&1
#exec 1>${logfile}
#exec 2>&1

state="$(cat /sys/class/net/$iface/operstate 2>/dev/null)"
if [ "$state" != "up" ]; then
	exit 0
fi

if wlan=$(iwconfig $iface 2>/dev/null | perl -0ne 'print int(eval "100*$3"), "% at $1, $2" if /ESSID:"(.+?)".*Bit Rate=(.+?\/s).*Link Quality=(\S+)/s'); then
fi
if [ -n "$stats" ]; then
    essid="${stats[0]}"
    speed="${stats[1]}"
    quality="${stats[2]}"
    info="$quality% at $essid, $speed" 
    for i in $(seq 0 $((${#thresholds[@]}-1))); do
        if [ $quality -le ${thresholds[i]} ]; then
            prefix=${prefixes[i]}
            color=${colors[i]}
            break
        fi
    done
fi

ipv4addrs=($(ip addr show $iface 2>/dev/null | perl -lne 'print $1 if /inet (\S+).*scope global/'))
ipv6addrs=($(ip addr show $iface 2>/dev/null | perl -lne 'print $1 if /inet6 (\S+).*scope global/'))

full_text="$prefix ${ipv4addrs[@]} ${ipv6addrs[0]} ($info)"
short_text="$prefix ${ipv4addrs[0]}"

exec >&3

echo -e $full_text
echo -e $short_text
[ -n "$color" ] && echo $color

exit 0

