#!/bin/bash
icons=('\uf434' '\uf432' '\uf04d')

if [ -n "$BLOCK_BUTTON" ]; then
    laptop-screen-toggle-layout
fi

current_layout=$(cat ${XDG_RUNTIME_DIR:-${HOME}/.local/var/run}/laptop-screen-toggle-layout/layout 2>/dev/null)

if [ "$current_layout" = "left-of" ]; then
    text=${icons[0]}
elif [ "$current_layout" = "right-of" ]; then
    text=${icons[1]}
elif [ "$current_layout" = "mirror" ]; then
    text=${icons[2]}
fi

[ -n "$text" ] && echo -e $text
exit 0
