#!/bin/bash
for output in $(xrandr --current | perl -lne 'print "$1,$2,$3" if /(\S+)\s+((?:dis)?connected)(?:\s+primary)?\s*([^\s(]*)/;'); do
    IFS="," read output_name output_state output_resolution <<< "${output}"
    if [ "$output_state" = "disconnected" ] && [ -n "$output_resolution" ]; then
        xrandr --output $output_name --off
    fi
done

exit 0
