#!/bin/bash
thresholds=(50 100)
prefixes=("" "")
muted_prefix=""
color="#839496"
muted_color="#dc322f"

card=${1:-0}
control=${2:-Master}

info=($(amixer -c $card get $control | perl -ne 'print "$1 $2\n" if /^\s*Mono:.*\[(.+)%\].*\[.*\].*\[(.+)\].*/'))

[ -z "${info}" ] && exit 0

volume=${info[0]}
status=${info[1]}

if [ $status = "off" ]; then
  prefix=$muted_prefix
  color=$muted_color
else
    for i in $(seq 0 $((${#thresholds[@]}-1))); do
        if [ $volume -le ${thresholds[i]} ]; then
            prefix=${prefixes[i]}
            break
        fi
    done
fi

short_text="$prefix $volume%"
full_text=$short_text

echo $full_text
echo $short_text
[ -n $color ] && echo $color

exit 0
