#!/bin/bash
thresholds=(75 100)
prefixes=("\uf027" "\uf028")
muted_prefix="\uf026"
color="#839496"
muted_color="#dc322f"

card=${1:-0}
control=${2:-Master}

scriptname="$(basename $0)"

logfile="${HOME}/.local/var/log/${scriptname}.log"
exec 3>&1
exec 1>${logfile}
exec 2>&1

if [ -n "$BLOCK_BUTTON" ]; then
    laptop-volume-set toggle
fi

info=($(amixer -c $card get $control | perl -ne 'print "$1 $2\n" if /^\s*Mono:.*\[(.+)%\].*\[.*\].*\[(.+)\].*/'))

[ -z "${info}" ] && exit 0

volume=${info[0]}
status=${info[1]}

if [ $status = "off" ]; then
  prefix=$muted_prefix
  color=$muted_color
else
    for i in $(seq 0 $((${#thresholds[@]}-1))); do
        if [ $volume -le ${thresholds[i]} ]; then
            prefix=${prefixes[i]}
            break
        fi
    done
fi

short_text="$prefix $volume%"
full_text=$short_text

exec >&3

echo -e $full_text
echo -e $short_text
[ -n $color ] && echo $color

exit 0
