#!/bin/bash
prefix="\uf023"

iface="${1:-ppp0}"

ipv4addrs=($(ip a s "${iface}" 2>/dev/null | perl -ne 'print "$1\n" if /inet (\S+).*scope global/'))
ipv6addrs=($(ip a s "${iface}" 2>/dev/null | perl -ne 'print "$1\n" if /inet6 (\S+).*scope global/'))
ipaddrs=("${ipv4addrs[@]}")
[ -n "${ipv6addrs[0]}" ] && ipaddrs=("${ipaddrs[@]}" "${ipv6addrs[0]}")

[ -z "${ipaddrs[*]}" ] && exit 0

full_text="${prefix} ${ipaddrs[*]}"
short_text="${prefix} ${ipaddrs[0]}"

echo -e "${full_text}"
echo -e "${short_text}"

exit 0
