#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2014 Mark Stillwell <mark@stillwell.me>
# with changes Copyright (C) 2014 Mark Stillwell <mark@stillwell.me>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

prefix="\uf023"

iface="${1:-bnep0}"

scriptname="$(basename $0)"

logfile="${HOME}/.local/var/log/${scriptname}.log"
exec 3>&1
exec 1>${logfile}
exec 2>&1

ipv4addrs=($(ip addr show $iface | perl -ne 'print "$1\n" if /inet (\S+).*scope global/'))
ipv6addrs=($(ip addr show $iface | perl -ne 'print "$1\n" if /inet6 (\S+).*scope global/'))
if [ ${#ipv4addrs} = 0 ] && [ ${#ipv6addrs} = 0 ]; then
    exit 0
fi

full_text="$prefix ${ipv4addrs[@]} ${ipv6addrs[0]}"
short_text="$prefix ${ipv4addrs[0]}"

vpn_name=$(nmcli con status | perl -ane 'print $F[0] if $F[3] eq "yes" and $F[4] eq "yes"')
if [ -n "$vpn_name" ]; then
    full_text="$full_text $vpn_name"
    short_text="$short_text $vpn_name"
fi

exec >&3

echo -e $full_text
echo -e $short_text
[ -n "$color" ] && echo $color

exit 0
