#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# with changes Copyright (C) 2014 Mark Stillwell <mark@stillwell.me>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

thresholds=(10 25 50 100)
prefixes=('' '' '' '')
colors=('#FF0000' '#FFFF00' '#FFFFFF' '#00FF00')

iface="${1:-wlan0}"

state="$(cat /sys/class/net/$iface/operstate)"
if [ "$state" != "up" ]; then
	exit 0
fi

ipaddrs=($(ip addr show $iface | perl -ne 'print "$1\n" if /inet (.+)\//'))
ipaddrs6=($(ip addr show $iface | perl -ne 'print "$1\n" if /inet6 (.+)\//'))

short_text="${ipaddrs[0]}"
full_text="${ipaddrs[@]} ${ipaddrs6[0]}"

oldIFS=$IFS
IFS=,
stats=($(iwconfig $iface | perl -0ne 'print "$1,$2,", eval "int(100*$3)" if /ESSID:"(.+?)".*Bit Rate=(.+?\/s).*Link Quality=([^\s]+)/ms;'))
IFS=$oldIFS
if [ -n "$stats" ]; then
    essid="${stats[0]}"
    quality="${stats[2]}"
    speed="${stats[1]}"
    full_text="$full_text ($quality% at $essid, $speed)" 
    for i in $(seq ${#thresholds}); do
        if [ $quality -le ${thresholds[i]} ]; then
            prefix=${prefixes[i]}
            color=${colors[i]}
            break
        fi
    done
fi

echo $prefix$full_text
echo $prefix$short_text
[ -n "$color" ] && echo $color

exit 0
