#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# with changes Copyright (C) 2014 Mark Stillwell <mark@stillwell.me>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

IFACE="$1"
[ -z "${IFACE}" ] && IFACE=wlan0

state="$(cat /sys/class/net/$IFACE/operstate)"

if [ "$state" != "up" ]; then
	exit 0
fi

ipaddrs=($(ip addr show $IFACE | perl -ne 'print "$1\n" if /inet (.+)\//'))
ipaddrs6=($(ip addr show $IFACE | perl -ne 'print "$1\n" if /inet6 (.+)\//'))

short_msg=" ${ipaddrs[0]}"
long_msg=" ${ipaddrs[@]} ${ipaddrs6[0]}"

stats=($(iwconfig wlan0 | perl -0ne 'print "$1\n$2\n", eval "int(100*$3)", "\n" if /ESSID:"(.+?)".*Bit Rate=(.+?)\s+Tx-Power=.*?Link Quality=(.+?)\s*Signal level=.*?/ms;'))
if [ -n "$stats" ]; then
    essid="${stats[0]}"
    quality="${stats[3]}"
    speed="${stats[1]} ${stats[2]}"
    long_msg="$long_msg ($quality% at $essid, $speed)" 
fi

echo $long_msg
echo $short_msg
